
INSERT INTO `groupe` VALUES (7, 'root', ' Compte administrateur');
INSERT INTO `groupe` VALUES (23, 'sas_admin', ' Administrateurs du SAS');
INSERT INTO `groupe` VALUES (4, 'kfet_admin', ' Ã‰tudiants autorisÃ©s Ã  administrer la KFet');
INSERT INTO `groupe` VALUES (5, 'kfet_barman', ' Ã‰tudiants autorisÃ©s Ã  tenir une permanence Ã  la KFet');
INSERT INTO `groupe` VALUES (8, 'moderateur_site', ' Les modÃ©rateurs des nouvelles et Ã©vÃ©nements sur le site');
INSERT INTO `groupe` VALUES (9, 'gestion_ae', ' Les gestionnaires de l''AE');
INSERT INTO `groupe` VALUES (11, 'matmatronch', ' Personnes autorisÃ©es Ã  rajouter des fiches de nouveaux Ã©tudiants');
INSERT INTO `groupe` VALUES (13, 'compta_admin', ' Ã‰tudiants autorisÃ©s Ã  administrer la comptabilitÃ©');
INSERT INTO `groupe` VALUES (15, 'foyer_admin', ' Ã‰tudiants autorisÃ©s Ã  administrer le Foyer');
INSERT INTO `groupe` VALUES (16, 'foyer_barman', ' Ã‰tudiants autorisÃ©s Ã  tenir une permanence au Foyer');
INSERT INTO `groupe` VALUES (20, 'cpt_bloque', ' Compte AE bloquÃ©');
INSERT INTO `groupe` VALUES (21, 'books_admin', ' Gestion des livres et bandes dessinÃ©es');
INSERT INTO `groupe` VALUES (24, 'bureau_belfort_vente', ' Personnes pouvant vendre au bureau de l''AE Ã  Belfort');
INSERT INTO `groupe` VALUES (25, 'bds-membre', ' Etudiants membres du BDS');
INSERT INTO `groupe` VALUES (26, 'gestion_salles', ' Personnes autorisÃ©es Ã  modÃ©rer les rÃ©servations de salle');
INSERT INTO `groupe` VALUES (27, 'gestion_emprunts', ' Personnes autorisÃ©es Ã  gÃ©rer les emprunts de matÃ©riel');
INSERT INTO `groupe` VALUES (28, 'gestion_localisation', ' Personnes autorisÃ©es Ã  gerer les lieux AE');
INSERT INTO `groupe` VALUES (29, 'blacklist_machines', 'Personne non autorisÃ© Ã  acheter de jetons');
INSERT INTO `groupe` VALUES (30, 'gestion_machines', 'Peronnes pouvant vendre des jetons et administrer l''outil');
INSERT INTO `groupe` VALUES (31, 'moderateur_forum', 'ModÃ©rateur gÃ©nÃ©raux de forum2');

INSERT INTO `d_folder` VALUES (1, 'Fichiers', NULL, NULL, '2006-08-22 00:00:00', NULL, NULL, 7, 7, 3549, 1);

INSERT INTO `sas_cat_photos` VALUES (1, 9, 142, 9, NULL, NULL, 'SAS', NULL, NULL, 1877, 1, NULL, NULL, NULL);

INSERT INTO `site_boites` VALUES ('Important', 'Bienvenue', 'La boite ''important'', situÃ©e tout en haut Ã  droite, Ã  cotÃ© du logo de l''ae. ');
INSERT INTO `site_boites` VALUES ('Weekly_photo', 'L''Ã©quipe du BDF', 'la phrase servant de lÃ©gende Ã  la photo de la semaine, dans les boites disponibles Ã  droite.');
INSERT INTO `site_boites` VALUES ('Anniversaire', 'Ils soufflent leurs bougies', 'La phrase permettant de souhaiter un bon anniversaire aux inscrits, Ã  droite.');
INSERT INTO `site_boites` VALUES ('Welcome', 'Bienvenue,', 'La phrase de bienvenue dans la boite de login du site, avant de proposer les diffÃ©rentes fonctionnalitÃ©s auxquelles l''Ã©tudiant a droit, Ã  gauche.');
INSERT INTO `site_boites` VALUES ('news_help', 'GrÃ¢ce Ã  cette page, vous allez pouvoir ajouter une nouvelle sur le site. Chaque nouvelle est composÃ©e d''un titre, d''un corps et d''une catÃ©gorie. Cette derniÃ¨re information permettra de positionner une icÃ´ne correspondant Ã  la nouvelle. Si le logo de votre activitÃ© n''y est pas, contactez les administrateurs.\n\nVotre nouvelle ne sera pas automatiquement ajoutÃ©e en premiÃ¨re page. Elle sera tout d''abord modÃ©rÃ©e par les modÃ©rateurs. Une fois cette opÃ©ration rÃ©alisÃ©e, elle sera visible. en premiÃ¨re page par tous les visiteurs.\n\nLa saisie d''une nouvelle se dÃ©roule en 3 Ã©tapes :\n\n   1. Saisie de la nouvelle\n   2. Visualisation de la nouvelle, et Ã©ventuellement, correction\n   3. Validation de la nouvelle pour modÃ©ration\n', 'Description de la page pour l''ajout de nouvelles');

INSERT INTO `site_parametres` VALUES ('closed', 'b:0;');
INSERT INTO `site_parametres` VALUES ('closed.eboutic', 'b:0;');

INSERT INTO `asso` VALUES (1, NULL, 'AE', 'ae', '', 'ae@utbm.fr', 'http://ae.utbm.fr/', NULL, NULL);
INSERT INTO `asso` VALUES (2, NULL, 'BDF', 'bdf', '6 Bd Anatole France\r\n90000 Belfort', 'bdf@utbm.fr', '', NULL, NULL);
INSERT INTO `asso` VALUES (3, NULL, 'BDS', 'bds', '6 Bd Anatole France\r\n90000 Belfort', 'bds@utbm.fr', 'http://bds.utbm.fr/', NULL, NULL);
INSERT INTO `asso` VALUES (10, 1, 'Pole artistique', 'pa', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `asso` VALUES (9, 1, 'Pole technique', 'pt', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `asso` VALUES (11, 1, 'Pole culturel', 'pc', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `asso` VALUES (12, 1, 'PÃ´le entraide et humanitaire', 'ph', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `asso` VALUES (13, 1, 'Grandes activitÃ©s', 'ga', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `asso` VALUES (14, 13, 'Integration', 'integ', '', 'integration@utbm.fr', '', NULL, NULL);
INSERT INTO `asso` VALUES (15, 13, 'Gala', 'gala', '', 'gala@utbm.fr', 'http://ae.utbm.fr/gala/', NULL, NULL);
INSERT INTO `asso` VALUES (16, 13, 'CongrÃ¨s', 'congres', '', 'congres@utbm.fr', 'http://ae.utbm.fr/congres/', NULL, NULL);
INSERT INTO `asso` VALUES (17, 13, 'Semaine de mars', 'semainemars', 'Semaine de Mars\r\n6 rue Anatole France\r\n90000 BELFORT', 'semainedemars@utbm.fr', '', NULL, NULL);
INSERT INTO `asso` VALUES (18, 13, 'Week-end Ã  l''UTBM', 'weutbm', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `asso` VALUES (19, 13, 'Festival du film d''un jour', 'ff1j', '', 'ff1j@utbm.fr', 'http://ae.utbm.fr/ff1j/', NULL, NULL);
INSERT INTO `asso` VALUES (20, 9, 'Club kart', 'club.kart', '', 'club.kart@utbm.fr', '', NULL, NULL);
INSERT INTO `asso` VALUES (21, 9, 'Club solex', 'club.solex', '', 'club.solex@utbm.fr', '', NULL, NULL);
INSERT INTO `asso` VALUES (22, 9, 'Mini-moto', 'mini.moto', '', 'mini.moto@utbm.fr', '', NULL, NULL);
INSERT INTO `asso` VALUES (23, 9, 'Lolut', 'lolut', '', 'lolut@utbm.fr', '', NULL, NULL);
INSERT INTO `asso` VALUES (24, 9, 'Unitec', 'unitec', '', 'unitec@utbm.fr', 'http://ae.utbm.fr/unitec/', NULL, NULL);
INSERT INTO `asso` VALUES (25, 9, 'Zenith', 'zenith', '', 'zenith@utbm.fr', 'http://ae.utbm.fr/zenith/', NULL, NULL);
INSERT INTO `asso` VALUES (26, 12, 'Petit gÃ©ni', 'petitgeni', '', 'petit.geni@utbm.fr', 'http://ae.utbm.fr/petitgeni/', NULL, NULL);
INSERT INTO `asso` VALUES (27, 12, 'Mat''Matronch', 'matmatronch', '', '', 'http://ae.utbm.fr/matmatronch/', NULL, NULL);
INSERT INTO `asso` VALUES (28, 12, 'Solidar''UT', 'solidarut', '', 'solidarut@utbm.fr', 'http://ae.utbm.fr/solidarut', NULL, NULL);
INSERT INTO `asso` VALUES (29, 12, 'Club welcome', 'welcome', '', 'welcome@utbm.fr', 'http://ae.utbm.fr/welcome/', NULL, NULL);
INSERT INTO `asso` VALUES (30, 12, '4L Trophy', '4ltrophy', '', '4l.trophy@utbm.fr', 'http://ae.utbm.fr/4ltrophy/', NULL, NULL);
INSERT INTO `asso` VALUES (31, 11, 'Aquariums', 'aqua', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `asso` VALUES (32, 11, 'BD dingue', 'bddingue', '', '', 'http://ae.utbm.fr/biblio/', NULL, NULL);
INSERT INTO `asso` VALUES (33, 11, 'BibliothÃ¨k Belfort', 'bibliothek', '', 'bibliothek@utbm.fr', 'http://ae.utbm.fr/biblio/', NULL, NULL);
INSERT INTO `asso` VALUES (34, 11, 'Club Billard', 'billard', '', 'club.billard@utbm.fr', '', NULL, NULL);
INSERT INTO `asso` VALUES (35, 11, 'Club Astro', 'astro', '', 'club.astro@utbm.fr', '', NULL, NULL);
INSERT INTO `asso` VALUES (36, 11, 'Club Echecs', 'echecs', '', 'club.echecs@utbm.fr', '', NULL, NULL);
INSERT INTO `asso` VALUES (37, 11, 'La BohÃ¨me', 'boheme', '', 'laboheme@utbm.fr', 'http://ae.utbm.fr/boheme/', NULL, NULL);
INSERT INTO `asso` VALUES (38, 11, 'Troll PenchÃ©', 'troll', '', 'troll.penche@utbm.fr', '', NULL, NULL);
INSERT INTO `asso` VALUES (39, 10, 'Arret Dessin', 'dessin', '', 'club.dessin@utbm.fr', '', NULL, NULL);
INSERT INTO `asso` VALUES (40, 10, 'Club Graff', 'club.graff', '', 'club.graff@utbm.fr', '', NULL, NULL);
INSERT INTO `asso` VALUES (41, 10, 'Club Jonglage', 'club.jonglage', '', 'club.jonglage@utbm.fr', '', NULL, NULL);
INSERT INTO `asso` VALUES (42, 10, 'Club Mix', 'club.mix', '', 'club.mix@utbm.fr', '', NULL, NULL);
INSERT INTO `asso` VALUES (43, 10, 'Reflex', 'Reflex', '', 'reflex@utbm.fr', 'http://ae.utbm.fr/reflex', NULL, NULL);
INSERT INTO `asso` VALUES (44, 10, 'Club Zik', 'club.zik', '', 'club.zik@utbm.fr', '', NULL, NULL);
INSERT INTO `asso` VALUES (45, 10, 'Club LumiÃ¨res', 'club.lumieres', '', 'club.lumieres@utbm.fr', 'http://ae.utbm.fr/cl/', NULL, NULL);
INSERT INTO `asso` VALUES (46, 10, 'Orchestre', 'orchestre', '', 'orchestre@utbm.fr', '', NULL, NULL);
INSERT INTO `asso` VALUES (47, 10, 'Prom''Art', 'promart', '', 'promart@utbm.fr', '', NULL, NULL);
INSERT INTO `asso` VALUES (48, 11, 'Seven''Art', 'sevenart', '', 'sevenart@utbm.fr', '', NULL, NULL);
INSERT INTO `asso` VALUES (49, 10, 'UTBM Productions', 'utprod', '', 'utbm-productions@utbm.fr', 'http://ae.utbm.fr/utprod/', NULL, NULL);
INSERT INTO `asso` VALUES (50, 11, 'UT Toons', 'uttoons', '', 'uttoons@utbm.fr', '', NULL, NULL);
INSERT INTO `asso` VALUES (51, NULL, 'CETU', 'cetu', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `asso` VALUES (52, NULL, 'Com''ET', 'comet', '55 faubourg des ancÃªtres \r\n90000 Belfort', 'contact@comet.asso.fr', 'en construction : comet.asso.fr', NULL, NULL);
INSERT INTO `asso` VALUES (53, NULL, 'Promo 05', 'promo05', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `asso` VALUES (54, NULL, 'Promo 03', 'promo03', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `asso` VALUES (55, 3, 'Edhec', 'edhec', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `asso` VALUES (56, 3, 'Paintball', 'paintball', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `asso` VALUES (57, NULL, 'Promo 04', 'promo04', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `asso` VALUES (58, NULL, 'Promo 06', 'promo06', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `asso` VALUES (59, NULL, 'Promo 07', 'promo07', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `asso` VALUES (60, NULL, 'Promo 01', 'promo01', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `asso` VALUES (61, NULL, 'Promo 02', 'promo02', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `asso` VALUES (62, 10, 'Club DDR', 'ClubDDR', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `asso` VALUES (63, 10, 'BigBand', 'bigband', '', 'bigband@utbm.fr', 'http://ae.utbm.fr/bigband', NULL, NULL);
INSERT INTO `asso` VALUES (64, 3, 'Ski-Ut', 'skiut', '', 'skiut2008@gmail.com', '', NULL, NULL);
INSERT INTO `asso` VALUES (67, NULL, 'Cosinus', 'cosinus', '', '', '', NULL, NULL);
INSERT INTO `asso` VALUES (68, 3, 'AÃ¯kido', 'aikido', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `asso` VALUES (69, 9, 'AÃ©ro''ut', 'aerout', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `asso` VALUES (70, NULL, 'PMAB', 'pmab', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `asso` VALUES (71, 81, 'Job-etu', 'aejobetu', '', '', '', NULL, NULL);
INSERT INTO `asso` VALUES (72, 81, 'La boutic', 'boutic', '6 Bd Anatole France\r\n90000 Belfort', '', 'http://ae.utbm.fr/e-boutic/', NULL, NULL);
INSERT INTO `asso` VALUES (73, 10, 'UTBM TV', 'utbmtv', '6 Bd Anatole France\r\n90000 Belfort', NULL, NULL, NULL, NULL);
INSERT INTO `asso` VALUES (74, 3, 'RAID', 'RAID', '6 Boulevard Anatole France\r\n90000 Belfort', NULL, NULL, NULL, NULL);
INSERT INTO `asso` VALUES (75, NULL, 'Promo 08', 'promo08', '8 bis rue de Delle\r\n90400 Sevenans', 'promo08@utbm.fr', 'http://ae.utbm.fr/promo08', NULL, NULL);
INSERT INTO `asso` VALUES (76, 10, 'UT ScÃ¨ne', 'utscene', '', NULL, NULL, NULL, NULL);
INSERT INTO `asso` VALUES (77, 11, 'Super Flux', 'superflux', '6 boulevard Anatole France\r\n90000 Belfort', NULL, NULL, NULL, NULL);
INSERT INTO `asso` VALUES (79, 11, 'Cuisine', 'cuisine', '', NULL, NULL, NULL, NULL);
INSERT INTO `asso` VALUES (81, 1, 'Pole services', 'ps', '', '', '', '', '');
INSERT INTO `asso` VALUES (82, 11, 'Club poker', 'club.poker', '', '', '', '', '');
INSERT INTO `asso` VALUES (83, 11, 'Club babyfoot', 'club.babyfoot', '', '', '', '', '');
INSERT INTO `asso` VALUES (84, 81, 'Laverie', 'laverie', '', '', '', '', '');
INSERT INTO `asso` VALUES (85, 81, 'Pret de matÃ©riel', 'pretmatos', '', '', '', '', '');
INSERT INTO `asso` VALUES (86, 10, 'Electrochoc', 'electrochoc', '', '', '', '', '');

-- @todo ajouter quelques utilisateurs
